# Generated by Django 5.0.7 on 2024-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Agendado para: ')),
                ('objective', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('departtmet_id', models.ManyToManyField(related_name='departments_id', to='departments.department')),
            ],
        ),
    ]
