# Generated by Django 5.0.7 on 2024-08-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.CharField(max_length=500)),
                ('department_id', models.ManyToManyField(related_name='departmant_org', to='departments.department')),
            ],
        ),
    ]
