# Generated by Django 5.0.7 on 2024-07-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em: ')),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='author.author')),
            ],
        ),
    ]
